platform :ios, '13.0'
use_frameworks! :linkage => :static

source 'https://cdn.cocoapods.org'

def pod_Common
  pod 'JSLayoutSizeFit', :path => '..', :subspecs => ['ExtensionForSwift']
  pod 'QMUIKit'
  pod 'Masonry'
  pod 'MPITextKit'
  pod 'SwiftLint', :configurations => ['Debug']
  pod "LookInsideServer", :git => "https://github.com/LookInsideApp/LookInside-Release.git", :configurations => ['Debug']
end

target 'JSLayoutSizeFitExample' do
  pod_Common
end

target 'JSLayoutSizeFitExampleMacOS' do
  pod_Common
end
