platform :ios, '15.0'
use_frameworks! :linkage => :static

source 'https://cdn.cocoapods.org'

def pod_Common
  pod 'JSLayoutSizeFit', :path => '..', :subspecs => ['ExtensionForSwift']
  pod 'QMUIKit'
  pod 'Masonry'
  pod 'MPITextKit'
  pod 'SwiftLint', :configurations => ['Debug']
  pod "LookInsideServer", :git => "https://github.com/LookInsideApp/LookInside-Release.git", :configurations => ['Debug']
end

target 'JSLayoutSizeFitExample' do
  pod_Common
end

target 'JSLayoutSizeFitExampleMacOS' do
  pod_Common
end

def set_deployment_target(target)
  target.build_configurations.each do |config|
    config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    set_deployment_target(target)
  end
end
